/**
 * Cleans common invalid syntaxes from JSON strings generated by LLMs,
 * such as mathematical expressions in numeric fields or raw newlines inside string values.
 * 
 * @param {string} jsonStr - JSON string to clean
 * @returns {string} - Cleaned JSON string
 */
export function cleanInvalidJSONSyntaxes(jsonStr) {
  if (typeof jsonStr !== 'string') return '';

  // 1. Fix math expressions in numeric fields (e.g., "skills_score": 0.85 * (100 + 85) / 3 = 61.67)
  jsonStr = jsonStr.replace(
    /("skills_score"|"experience_score"|"quality_score"|"weighted_score")\s*:\s*([^,\}\n\]]+)/g,
    (match, key, val) => {
      val = val.trim();
      // If it contains '=', extract the number after '='
      if (val.includes('=')) {
        const parts = val.split('=');
        const numPart = parts[parts.length - 1].trim();
        const numMatch = numPart.match(/[\d\.]+/);
        if (numMatch) return `${key}: ${numMatch[0]}`;
      }
      
      // Extract numbers
      const numMatch = val.match(/[\d\.]+/g);
      if (numMatch && numMatch.length > 0) {
        if (/^\d+(\.\d+)?$/.test(val)) {
          return `${key}: ${val}`;
        }
        return `${key}: ${numMatch[numMatch.length - 1]}`;
      }
      return match;
    }
  );

  // 2. Fix unescaped raw newlines inside JSON string values.
  let inString = false;
  let chars = jsonStr.split('');
  for (let i = 0; i < chars.length; i++) {
    if (chars[i] === '"' && chars[i - 1] !== '\\') {
      inString = !inString;
    }
    if (inString && chars[i] === '\n') {
      chars[i] = '\\n';
    }
  }
  jsonStr = chars.join('');

  return jsonStr;
}

/**
 * Cleans the input text by identifying the start of a JSON object/array
 * and finding its corresponding closing bracket.
 * 
 * @param {string} text - Raw output from AI model
 * @returns {string} - Cleaned JSON string or the original trimmed text if no match found
 */
export function cleanJSON(text) {
  if (typeof text !== 'string') return '';
  text = text.trim();
  
  // Find the first occurrence of { or [
  const startObj = text.indexOf('{');
  const startArr = text.indexOf('[');
  
  let start = -1;
  let end = -1;
  let bracketType = '';

  if (startObj !== -1 && (startArr === -1 || startObj < startArr)) {
    start = startObj;
    bracketType = '{';
  } else if (startArr !== -1) {
    start = startArr;
    bracketType = '[';
  }

  if (start === -1) return text;

  // Simple bracket matcher to find the matching closing bracket
  const closingType = bracketType === '{' ? '}' : ']';
  let stack = 0;
  for (let i = start; i < text.length; i++) {
    if (text[i] === bracketType) {
      stack++;
    } else if (text[i] === closingType) {
      stack--;
      if (stack === 0) {
        end = i;
        break;
      }
    }
  }

  if (start !== -1 && end !== -1) {
    return text.substring(start, end + 1);
  }
  
  return text;
}

/**
 * Parses the AI text response to JSON, extracting the JSON structure first.
 * Throws an error if text is empty, not a string, or contains invalid/unparseable JSON.
 * 
 * @param {string} text - AI model response
 * @returns {Object|Array} - Parsed JSON object or array
 */
export function parseAIResponse(text) {
  if (!text || typeof text !== 'string') {
    throw new Error('AI response is empty or not a string');
  }

  let cleaned = cleanJSON(text);
  cleaned = cleanInvalidJSONSyntaxes(cleaned);
  
  try {
    return JSON.parse(cleaned);
  } catch (error) {
    throw new Error(`Failed to parse AI response as JSON: ${error.message}. Cleaned text: "${cleaned}"`);
  }
}

